name: mine_field
description: Pequeno projeto para estudo da Fluent Ui.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  fluent_ui: ^4.1.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  freezed_annotation: ^2.1.0
  hooks_riverpod: ^2.0.0-dev.9
  intl: ^0.17.0
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  msix: ^3.6.3

msix_config:
  display_name: Campo Minado
  publisher_display_name: Jilly Taboga
  identity_name: jilly.developer
  msix_version: 1.0.0.0

flutter:
